version: '3.8'

services:

  postgres:
    container_name: postgres-test
    image: postgres:14.1-alpine
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - .data/postgresql-data:/var/lib/postgresql/data
    networks:
      - ws-network

  admin:
    image: adminer
    restart: always
    depends_on: 
      - postgres
    ports:
      - 8080:8080


  mongodb:
    image : mongo
    container_name: mongodb-test
    ports:
      - "27017:27017"
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
      - MONGO_INITDB_DATABASE=$MONGO_DB
    volumes:
      - .data/mongo-data:/data/db
    networks:
      - ws-network
    restart: unless-stopped

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    env_file:
      - .env
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=$MONGO_USERNAME
      - ME_CONFIG_MONGODB_ADMINPASSWORD=$MONGO_PASSWORD
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
    volumes:
      - .data/mongo-data
    depends_on:
      - mongodb
    networks:
      - ws-network
    ports:
      - 8081:8081

networks:
  ws-network: